-- Generated by scripts/generate-seed.ts — do not edit by hand.
-- Safe to re-run: ids are deterministic and conflicts are ignored.
begin;

-- users
insert into public.users (id, username, display_name, avatar_url, bio, profile_visibility, created_at) values
  ('a22030a2-8ed5-4c29-bcd2-93c5d2420099', 'jeongmin', 'Jeong Min', null, 'Building Witness. Comparing with past self.', 'public', '2026-01-10T09:00:00Z'),
  ('08a52506-3c26-450a-bce9-64323bf7319f', 'david', 'David', null, 'Designing Witness.', 'public', '2026-01-12T09:00:00Z'),
  ('4e74d342-d218-4d52-8601-748c2e556d50', 'runner_kim', 'Kim', null, 'Training for a marathon.', 'followers_only', '2026-02-01T09:00:00Z'),
  ('827db36d-169f-4d92-9ff3-5f97cfecfd92', 'quiet_lee', 'Lee', null, 'Writing for a small circle.', 'followers_only', '2026-02-10T09:00:00Z'),
  ('ea826721-4d66-4b03-b8a8-7f9617ccc515', 'solo_park', 'Park', null, 'Keeping this to myself.', 'private', '2026-02-15T09:00:00Z')
on conflict do nothing;

-- user_settings
insert into public.user_settings (user_id, notify_candle, notify_comment, notify_follow_request, notify_follow_accepted, language) values
  ('a22030a2-8ed5-4c29-bcd2-93c5d2420099', true, true, true, true, 'en'),
  ('08a52506-3c26-450a-bce9-64323bf7319f', true, true, true, true, 'en'),
  ('4e74d342-d218-4d52-8601-748c2e556d50', true, true, true, true, 'en'),
  ('827db36d-169f-4d92-9ff3-5f97cfecfd92', true, true, true, true, 'en'),
  ('ea826721-4d66-4b03-b8a8-7f9617ccc515', true, true, true, true, 'en')
on conflict do nothing;

-- tags
insert into public.tags (id, name) values
  ('584ecaa1-e773-4178-b3f5-4891e3043969', 'coding'),
  ('450643e9-2707-699b-3299-b27b61fd9472', 'exercise'),
  ('d1fa8494-2c32-84c4-fe2d-4c2a88191cb0', 'reading'),
  ('8d411870-d1aa-bf62-6aa5-01a1272bf21c', 'mindfulness')
on conflict do nothing;

-- posts
insert into public.posts (id, user_id, content, is_hidden, created_at, updated_at) values
  ('f4ca36d5-f89b-9cee-0d56-a005f9966bee', 'a22030a2-8ed5-4c29-bcd2-93c5d2420099', 'Finished the Auth flow today. Small win, feels good.', false, '2026-08-20T10:00:00Z', '2026-08-20T10:00:00Z'),
  ('17c52d88-8239-9846-3a84-55c474cb7e1a', 'a22030a2-8ed5-4c29-bcd2-93c5d2420099', 'Two chapters in on Atomic Habits.', false, '2026-08-19T20:00:00Z', '2026-08-19T20:00:00Z'),
  ('1a9a2861-26c8-61ba-77f6-336e9d47207e', '4e74d342-d218-4d52-8601-748c2e556d50', '10k run this morning, legs are dead.', false, '2026-08-20T07:30:00Z', '2026-08-20T07:30:00Z'),
  ('aaa0a43a-1047-271c-5dd3-bdbfff911664', '4e74d342-d218-4d52-8601-748c2e556d50', 'Ran 12km this morning. Legs held up better than last week.', false, '2026-08-23T07:30:00Z', '2026-08-23T07:30:00Z'),
  ('8f65f36a-2417-0d56-9da3-43d824291183', '827db36d-169f-4d92-9ff3-5f97cfecfd92', 'Finished the second chapter. Slower than I hoped, but done.', false, '2026-08-24T21:00:00Z', '2026-08-24T21:00:00Z'),
  ('ecf4532d-f68f-f05b-40ee-04e577f7c19d', 'ea826721-4d66-4b03-b8a8-7f9617ccc515', 'Day 30. Still going.', false, '2026-08-24T22:00:00Z', '2026-08-24T22:00:00Z')
on conflict do nothing;

-- post_tags
insert into public.post_tags (post_id, tag_id) values
  ('f4ca36d5-f89b-9cee-0d56-a005f9966bee', '584ecaa1-e773-4178-b3f5-4891e3043969'),
  ('17c52d88-8239-9846-3a84-55c474cb7e1a', 'd1fa8494-2c32-84c4-fe2d-4c2a88191cb0'),
  ('1a9a2861-26c8-61ba-77f6-336e9d47207e', '450643e9-2707-699b-3299-b27b61fd9472')
on conflict do nothing;

-- goals
insert into public.goals (id, user_id, title, description, status, cadence_type, cadence_config, streak_count, last_recorded_at, created_at) values
  ('028cb70f-0c05-23de-fc92-9a695ee674ee', 'a22030a2-8ed5-4c29-bcd2-93c5d2420099', 'Ship Witness MVP', null, 'active', 'daily', '{"type":"daily"}', 3, '2026-08-20T09:00:00Z', '2026-01-15T09:00:00Z'),
  ('4ba13114-9099-fde8-c0d5-72d9cce8ef8e', 'a22030a2-8ed5-4c29-bcd2-93c5d2420099', 'Read one book a month', null, 'active', 'weekly_count', '{"type":"weekly_count","target":2}', 1, '2026-08-17T09:00:00Z', '2026-01-20T09:00:00Z'),
  ('65ac29b3-32ec-e90d-082f-54094264e682', 'a22030a2-8ed5-4c29-bcd2-93c5d2420099', 'Learn Korean calligraphy', null, 'planned', null, null, 0, null, '2026-02-01T09:00:00Z'),
  ('623eeeff-d52c-2387-8970-22c9b7de2524', '08a52506-3c26-450a-bce9-64323bf7319f', 'Sketch every morning', null, 'active', 'daily', '{"type":"daily"}', 5, '2026-08-24T08:00:00Z', '2026-01-12T09:00:00Z'),
  ('000c1782-310f-45f7-8422-05572f0e66bc', '4e74d342-d218-4d52-8601-748c2e556d50', 'Marathon training', null, 'active', 'weekly_count', '{"type":"weekly_count","target":4}', 2, '2026-08-23T07:30:00Z', '2026-02-01T09:00:00Z')
on conflict do nothing;

-- post_goals
insert into public.post_goals (post_id, goal_id) values
  ('f4ca36d5-f89b-9cee-0d56-a005f9966bee', '028cb70f-0c05-23de-fc92-9a695ee674ee'),
  ('17c52d88-8239-9846-3a84-55c474cb7e1a', '4ba13114-9099-fde8-c0d5-72d9cce8ef8e'),
  ('1a9a2861-26c8-61ba-77f6-336e9d47207e', '000c1782-310f-45f7-8422-05572f0e66bc'),
  ('aaa0a43a-1047-271c-5dd3-bdbfff911664', '000c1782-310f-45f7-8422-05572f0e66bc')
on conflict do nothing;

-- follows
insert into public.follows (id, follower_id, followee_id, status, created_at, accepted_at) values
  ('3b59a7c5-f49c-9d5e-b6ef-82d50c930b77', '08a52506-3c26-450a-bce9-64323bf7319f', 'a22030a2-8ed5-4c29-bcd2-93c5d2420099', 'accepted', '2026-01-13T09:00:00Z', '2026-01-13T09:05:00Z'),
  ('b7956827-b2f1-02bb-cfce-7573491467d5', '4e74d342-d218-4d52-8601-748c2e556d50', 'a22030a2-8ed5-4c29-bcd2-93c5d2420099', 'pending', '2026-08-19T12:00:00Z', null),
  ('0ada8ecb-3215-241a-538b-e07164a8fd75', 'a22030a2-8ed5-4c29-bcd2-93c5d2420099', '4e74d342-d218-4d52-8601-748c2e556d50', 'accepted', '2026-02-05T09:00:00Z', '2026-02-05T09:05:00Z')
on conflict do nothing;

-- candle_lights
insert into public.candle_lights (id, post_id, user_id, created_at) values
  ('60974082-aa64-fee9-a0b6-92f01f035839', 'f4ca36d5-f89b-9cee-0d56-a005f9966bee', '08a52506-3c26-450a-bce9-64323bf7319f', '2026-08-20T10:15:00Z')
on conflict do nothing;

-- comments
insert into public.comments (id, post_id, user_id, content, created_at) values
  ('6a425ad7-4c41-5ba9-a709-a55dfac283f3', 'f4ca36d5-f89b-9cee-0d56-a005f9966bee', '08a52506-3c26-450a-bce9-64323bf7319f', 'Nice work on the auth flow!', '2026-08-20T10:20:00Z')
on conflict do nothing;

-- notifications
insert into public.notifications (id, sender_id, receiver_id, type, post_id, is_read, created_at) values
  ('67a8809a-bf71-5dbe-de87-291bf7851b54', '08a52506-3c26-450a-bce9-64323bf7319f', 'a22030a2-8ed5-4c29-bcd2-93c5d2420099', 'candle', 'f4ca36d5-f89b-9cee-0d56-a005f9966bee', false, '2026-08-20T10:15:00Z'),
  ('506f4b27-0f99-0215-a872-7d2534ee6b54', '08a52506-3c26-450a-bce9-64323bf7319f', 'a22030a2-8ed5-4c29-bcd2-93c5d2420099', 'comment', 'f4ca36d5-f89b-9cee-0d56-a005f9966bee', false, '2026-08-20T10:20:00Z'),
  ('724a1e22-8b98-beb9-7696-014d8e435abe', '4e74d342-d218-4d52-8601-748c2e556d50', 'a22030a2-8ed5-4c29-bcd2-93c5d2420099', 'follow_request', null, false, '2026-08-19T12:00:00Z'),
  ('d74723c5-af8a-e1f7-6446-eeb11c636f58', '4e74d342-d218-4d52-8601-748c2e556d50', 'a22030a2-8ed5-4c29-bcd2-93c5d2420099', 'follow_accepted', null, true, '2026-02-05T09:00:00Z'),
  ('5ce1d190-dca4-bb5f-1b65-9a9ca78e8b91', '08a52506-3c26-450a-bce9-64323bf7319f', 'a22030a2-8ed5-4c29-bcd2-93c5d2420099', 'candle', '17c52d88-8239-9846-3a84-55c474cb7e1a', true, '2026-08-15T14:00:00Z')
on conflict do nothing;

commit;
