/**
 * Emits seed SQL from the mock data layer.
 *
 *   npx tsx scripts/generate-seed.ts > seed.sql
 *
 * Then paste seed.sql into the Supabase SQL editor.
 *
 * Why generate rather than hand-write: the fixtures already describe the
 * exact scenario the RLS policies need to be tested against (a public
 * account, a followers-only account that is followed, one that isn't, and a
 * private account). Transcribing them by hand creates a second copy that
 * drifts. Re-run this whenever the fixtures change.
 *
 * Mock ids like 'post-1' are not UUIDs, so every id is mapped through a
 * deterministic hash. The same mock id always produces the same UUID, which
 * keeps foreign keys intact and makes re-running the script idempotent.
 */

import crypto from 'node:crypto'

import { mockUsers, mockUserSettings } from '../lib/mock-data/users'
import { mockTags } from '../lib/mock-data/tags'
import { mockPosts, mockPostTags } from '../lib/mock-data/posts'
import { mockGoals } from '../lib/mock-data/goals'
import { mockPostGoals } from '../lib/mock-data/post-goals'
import { mockFollows } from '../lib/mock-data/follows'
import { mockCandles, mockComments } from '../lib/mock-data/interactions'
import { mockNotifications } from '../lib/mock-data/notifications'

/**
 * Real auth.users UUIDs, copied from the Supabase dashboard after creating
 * each account with Auto Confirm enabled.
 *
 * public.users.id is a foreign key to auth.users.id, so these cannot be
 * invented — the accounts must exist first.
 */
const AUTH_UUIDS: Record<string, string> = {
  'user-1': 'a22030a2-8ed5-4c29-bcd2-93c5d2420099',
  'user-2': '08a52506-3c26-450a-bce9-64323bf7319f',
  'user-3': '4e74d342-d218-4d52-8601-748c2e556d50',
  'user-4': '827db36d-169f-4d92-9ff3-5f97cfecfd92',
  'user-5': 'ea826721-4d66-4b03-b8a8-7f9617ccc515',
}

/** Deterministic UUID for any non-user mock id. */
function uuidFor(mockId: string): string {
  if (AUTH_UUIDS[mockId]) return AUTH_UUIDS[mockId]

  const h = crypto.createHash('md5').update(mockId).digest('hex')
  return [
    h.slice(0, 8),
    h.slice(8, 12),
    h.slice(12, 16),
    h.slice(16, 20),
    h.slice(20, 32),
  ].join('-')
}

function sql(value: unknown): string {
  if (value === null || value === undefined) return 'null'
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  if (typeof value === 'number') return String(value)
  return `'${String(value).replace(/'/g, "''")}'`
}

function id(value: string): string {
  return sql(uuidFor(value))
}

const out: string[] = []

function section(title: string) {
  out.push(``, `-- ${title}`)
}

function insert(table: string, columns: string[], rows: string[][]) {
  if (rows.length === 0) return
  out.push(
    `insert into public.${table} (${columns.join(', ')}) values`,
    rows.map((r) => `  (${r.join(', ')})`).join(',\n') +
      '\non conflict do nothing;'
  )
}

const missing = Object.entries(AUTH_UUIDS).filter(([, v]) =>
  v.startsWith('PASTE_')
)
if (missing.length > 0) {
  console.error(
    `Fill in AUTH_UUIDS first — still placeholder: ${missing
      .map(([k]) => k)
      .join(', ')}`
  )
  process.exit(1)
}

out.push(
  '-- Generated by scripts/generate-seed.ts — do not edit by hand.',
  '-- Safe to re-run: ids are deterministic and conflicts are ignored.',
  'begin;'
)

section('users')
insert(
  'users',
  [
    'id',
    'username',
    'display_name',
    'avatar_url',
    'bio',
    'profile_visibility',
    'created_at',
  ],
  mockUsers.map((u) => [
    id(u.id),
    sql(u.username),
    sql(u.display_name),
    sql(u.avatar_url),
    sql(u.bio),
    sql(u.profile_visibility),
    sql(u.created_at),
  ])
)

section('user_settings')
insert(
  'user_settings',
  [
    'user_id',
    'notify_candle',
    'notify_comment',
    'notify_follow_request',
    'notify_follow_accepted',
    'language',
  ],
  mockUserSettings.map((s) => [
    id(s.user_id),
    sql(s.notify_candle),
    sql(s.notify_comment),
    sql(s.notify_follow_request),
    sql(s.notify_follow_accepted),
    sql(s.language),
  ])
)

section('tags')
insert(
  'tags',
  ['id', 'name'],
  mockTags.map((t) => [id(t.id), sql(t.name)])
)

section('posts')
insert(
  'posts',
  ['id', 'user_id', 'content', 'is_hidden', 'created_at', 'updated_at'],
  mockPosts.map((p) => [
    id(p.id),
    id(p.user_id),
    sql(p.content),
    sql(p.is_hidden),
    sql(p.created_at),
    sql(p.updated_at),
  ])
)

section('post_tags')
insert(
  'post_tags',
  ['post_id', 'tag_id'],
  mockPostTags.map((pt) => [id(pt.post_id), id(pt.tag_id)])
)

section('goals')
insert(
  'goals',
  [
    'id',
    'user_id',
    'title',
    'description',
    'status',
    'cadence_type',
    'cadence_config',
    'streak_count',
    'last_recorded_at',
    'created_at',
  ],
  mockGoals.map((g) => [
    id(g.id),
    id(g.user_id),
    sql(g.title),
    sql(g.description),
    sql(g.status),
    sql(g.cadence_type),
    g.cadence_config ? sql(JSON.stringify(g.cadence_config)) : 'null',
    sql(g.streak_count),
    sql(g.last_recorded_at),
    sql(g.created_at),
  ])
)

section('post_goals')
insert(
  'post_goals',
  ['post_id', 'goal_id'],
  mockPostGoals.map((pg) => [id(pg.post_id), id(pg.goal_id)])
)

section('follows')
insert(
  'follows',
  ['id', 'follower_id', 'followee_id', 'status', 'created_at', 'accepted_at'],
  mockFollows.map((f) => [
    id(f.id),
    id(f.follower_id),
    id(f.followee_id),
    sql(f.status),
    sql(f.created_at),
    sql(f.accepted_at),
  ])
)

section('candle_lights')
insert(
  'candle_lights',
  ['id', 'post_id', 'user_id', 'created_at'],
  mockCandles.map((c) => [
    id(c.id),
    id(c.post_id),
    id(c.user_id),
    sql(c.created_at),
  ])
)

section('comments')
insert(
  'comments',
  ['id', 'post_id', 'user_id', 'content', 'created_at'],
  mockComments.map((c) => [
    id(c.id),
    id(c.post_id),
    id(c.user_id),
    sql(c.content),
    sql(c.created_at),
  ])
)

section('notifications')
insert(
  'notifications',
  ['id', 'sender_id', 'receiver_id', 'type', 'post_id', 'is_read', 'created_at'],
  mockNotifications.map((n) => [
    id(n.id),
    id(n.sender_id),
    id(n.receiver_id),
    sql(n.type),
    n.post_id ? id(n.post_id) : 'null',
    sql(n.is_read),
    sql(n.created_at),
  ])
)

out.push('', 'commit;')

console.log(out.join('\n'))